[package]
name = "ic-archives-fs"
version = "0.1.0"
edition = "2021"
description = "Opens archives as folders in a panel"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ic-plugin-api = { workspace = true }
zip = "0.6.6"
tar = "0.4.40"
flate2 = "1.0.30"
bzip2 = "0.4.4"
chrono = "0.4"

[features]
default = ["export-abi"]
export-abi = []

[dev-dependencies]
serde_json = { workspace = true }
ic-plugin-api = { workspace = true, features = ["testing"] }
